# Generated by Django 5.1.4 on 2024-12-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
